project:
  type: website
  output-dir: docs

website:
  title: "HOME"
  description:
    All Things Me.
  site-url: "https://tiffany-ngli.github.io/BLOG/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: minty
    toc: false

editor:
  mode: source